"""
Generates radar-*.svg, stat-card-*.svg, and card-*.svg into assets/,
using only the Python standard library and the GitHub REST API.

Run locally:
    GH_LOGIN=HarisMajeed05 GITHUB_TOKEN=<token> python3 scripts/generate_assets.py

In CI, GH_LOGIN and GITHUB_TOKEN are supplied by the workflow automatically.

What's live vs static:
  - Language radar: computed live from your public repos' actual language
    bytes (GitHub's /repos/{owner}/{repo}/languages endpoint).
  - Stat card: live public repo count, star count, top language.
  - Project cards: live stars/forks/language for whichever repos are listed
    in assets/projects.json. The description in that file overrides GitHub's
    if present; otherwise it uses GitHub's repo description.
  - Self-rated skill radar: NOT computed, it's your opinion. Edit the
    values in assets/skills.json by hand.
  - Portrait: NOT regenerated by this script. It's a one-time render from a
    photo (see scripts/dotify_notes.md) and doesn't need to change on a
    schedule the way live stats do.
"""

import json
import math
import os
import urllib.request
import urllib.error

GH_LOGIN = os.environ.get("GH_LOGIN", "").strip()
TOKEN = os.environ.get("GITHUB_TOKEN", "").strip()
ASSETS_DIR = os.path.join(os.path.dirname(__file__), "..", "assets")


def gh_get(path):
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": f"{GH_LOGIN or 'profile-readme'}-asset-generator",
            **({"Authorization": f"Bearer {TOKEN}"} if TOKEN else {}),
        },
    )
    with urllib.request.urlopen(req) as resp:
        return json.load(resp)


def fetch_public_repos():
    repos, page = [], 1
    while True:
        batch = gh_get(f"/users/{GH_LOGIN}/repos?per_page=100&page={page}&type=owner")
        if not batch:
            break
        repos.extend(r for r in batch if not r["private"] and not r["fork"])
        if len(batch) < 100:
            break
        page += 1
    return repos


def fetch_languages(repo_name):
    try:
        return gh_get(f"/repos/{GH_LOGIN}/{repo_name}/languages")
    except urllib.error.HTTPError:
        return {}


# ---------- radar rendering ----------

def radar_svg(title, axes, color_fill, color_line, color_text, show_pct=False):
    n = len(axes)
    size = 620
    cx, cy = size / 2, size / 2
    R = 130
    step = 2 * math.pi / n

    def point(value, i):
        angle = -math.pi / 2 + i * step
        r = (value / 100) * R
        return cx + r * math.cos(angle), cy + r * math.sin(angle)

    parts = [f'<svg width="{size}" height="{size}" viewBox="0 0 {size} {size}" '
             f'xmlns="http://www.w3.org/2000/svg" font-family="JetBrains Mono, monospace">']
    parts.append(f'<text x="{size/2}" y="32" text-anchor="middle" font-size="17" '
                 f'fill="{color_text}" font-weight="600">{title}</text>')
    for ring in (0.25, 0.5, 0.75, 1.0):
        pts = " ".join(f"{x:.1f},{y:.1f}" for x, y in (point(ring * 100, i) for i in range(n)))
        parts.append(f'<polygon points="{pts}" fill="none" stroke="{color_line}" '
                     f'stroke-opacity="0.18" stroke-width="1"/>')
    for i, (label, value) in enumerate(axes):
        angle = -math.pi / 2 + i * step
        lx, ly = cx + (R + 40) * math.cos(angle), cy + (R + 40) * math.sin(angle)
        parts.append(f'<line x1="{cx}" y1="{cy}" x2="{cx+R*math.cos(angle):.1f}" '
                     f'y2="{cy+R*math.sin(angle):.1f}" stroke="{color_line}" '
                     f'stroke-opacity="0.18" stroke-width="1"/>')
        anchor = "middle"
        if math.cos(angle) > 0.3:
            anchor = "start"
        elif math.cos(angle) < -0.3:
            anchor = "end"
        suffix = "%" if show_pct else ""
        parts.append(f'<text x="{lx:.1f}" y="{ly:.1f}" text-anchor="{anchor}" '
                     f'font-size="12.5" fill="{color_text}" dominant-baseline="middle">'
                     f'{label} ({value}{suffix})</text>')
    pts = [point(v, i) for i, (l, v) in enumerate(axes)]
    pts_str = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
    parts.append(f'<polygon points="{pts_str}" fill="{color_fill}" fill-opacity="0.35" '
                 f'stroke="{color_fill}" stroke-width="2"/>')
    for x, y in pts:
        parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="3.5" fill="{color_fill}"/>')
    parts.append("</svg>")
    return "\n".join(parts)


def build_self_rated_radar():
    skills_path = os.path.join(ASSETS_DIR, "skills.json")
    with open(skills_path) as f:
        data = json.load(f)
    axes = [(a["label"], a["value"]) for a in data["axes"]]
    write(radar_svg("Skill Radar (self-rated)", axes, "#39D353", "#8B98A5", "#E6EDF3"),
          "radar-dark.svg")
    write(radar_svg("Skill Radar (self-rated)", axes, "#1a7f37", "#57606a", "#1F2328"),
          "radar-light.svg")


def build_language_radar(repos):
    totals = {}
    for r in repos:
        langs = fetch_languages(r["name"])
        for name, size in langs.items():
            totals[name] = totals.get(name, 0) + size
    total = sum(totals.values()) or 1
    top = sorted(totals.items(), key=lambda x: -x[1])[:6]
    axes = [(name, round(size / total * 100)) for name, size in top]
    write(radar_svg("Language Radar (live)", axes, "#33C7FF", "#8B98A5", "#E6EDF3", show_pct=True),
          "radar-langs-dark.svg")
    write(radar_svg("Language Radar (live)", axes, "#0969da", "#57606a", "#1F2328", show_pct=True),
          "radar-langs-light.svg")
    return totals


# ---------- stat card ----------

def stat_card_svg(stats, color_text, color_val, stroke):
    w, h = 620, 130
    n = len(stats)
    cell = w / n
    parts = [f'<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}" '
             f'xmlns="http://www.w3.org/2000/svg" font-family="JetBrains Mono, monospace">']
    parts.append(f'<rect x="1" y="1" width="{w-2}" height="{h-2}" rx="10" '
                 f'fill="none" stroke="{stroke}" stroke-opacity="0.25"/>')
    for i, (label, value) in enumerate(stats):
        x = cell * i + cell / 2
        parts.append(f'<text x="{x}" y="58" text-anchor="middle" font-size="28" '
                     f'font-weight="700" fill="{color_val}">{value}</text>')
        parts.append(f'<text x="{x}" y="84" text-anchor="middle" font-size="12" '
                     f'fill="{color_text}">{label}</text>')
        if i < n - 1:
            parts.append(f'<line x1="{cell*(i+1)}" y1="20" x2="{cell*(i+1)}" '
                         f'y2="{h-20}" stroke="{stroke}" stroke-opacity="0.15"/>')
    parts.append("</svg>")
    return "\n".join(parts)


def build_stat_card(repos, lang_totals):
    total_stars = sum(r["stargazers_count"] for r in repos)
    top_lang = max(lang_totals.items(), key=lambda x: x[1])[0] if lang_totals else "-"
    stats = [
        ("public repos", str(len(repos))),
        ("total stars", str(total_stars)),
        ("top language", top_lang),
    ]
    write(stat_card_svg(stats, "#8B98A5", "#39D353", "#8B98A5"), "stat-card-dark.svg")
    write(stat_card_svg(stats, "#57606a", "#1a7f37", "#57606a"), "stat-card-light.svg")


# ---------- project cards ----------

def wrap(text, width=46, max_lines=3):
    if not text:
        return []
    words, lines, cur = text.split(), [], ""
    for w in words:
        test = (cur + " " + w).strip()
        if len(test) > width:
            lines.append(cur)
            cur = w
        else:
            cur = test
    if cur:
        lines.append(cur)
    return lines[:max_lines]


def card_svg(name, desc, stack, title_c, text_c, stroke, tag_bg, tag_text):
    w, h = 420, 180
    parts = [f'<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}" '
             f'xmlns="http://www.w3.org/2000/svg" font-family="JetBrains Mono, monospace">']
    parts.append(f'<rect x="1" y="1" width="{w-2}" height="{h-2}" rx="10" '
                 f'fill="none" stroke="{stroke}" stroke-opacity="0.3"/>')
    parts.append(f'<text x="20" y="34" font-size="16" font-weight="700" fill="{title_c}">{name}</text>')
    for i, line in enumerate(wrap(desc)):
        parts.append(f'<text x="20" y="{58+i*18}" font-size="12" fill="{text_c}">{line}</text>')
    tx, ty = 20, h - 34
    for tag in stack[:5]:
        tw = len(tag) * 7 + 16
        parts.append(f'<rect x="{tx}" y="{ty}" width="{tw}" height="22" rx="11" fill="{tag_bg}"/>')
        parts.append(f'<text x="{tx+tw/2}" y="{ty+15}" text-anchor="middle" '
                     f'font-size="10.5" fill="{tag_text}">{tag}</text>')
        tx += tw + 8
    parts.append("</svg>")
    return "\n".join(parts)


def build_project_cards(repos_by_name):
    proj_path = os.path.join(ASSETS_DIR, "projects.json")
    with open(proj_path) as f:
        wanted = json.load(f)["projects"]

    dark = dict(title_c="#E6EDF3", text_c="#8B98A5", stroke="#8B98A5", tag_bg="#161b22", tag_text="#39D353")
    light = dict(title_c="#1F2328", text_c="#57606a", stroke="#57606a", tag_bg="#f6f8fa", tag_text="#1a7f37")

    for p in wanted:
        repo = repos_by_name.get(p["repo"])
        desc = p.get("description") or (repo["description"] if repo else "")
        stack = p.get("stack") or ([repo["language"]] if repo and repo["language"] else [])
        slug = p["repo"].lower()
        write(card_svg(p["repo"], desc, stack, **dark), f"card-{slug}-dark.svg")
        write(card_svg(p["repo"], desc, stack, **light), f"card-{slug}-light.svg")


# ---------- io ----------

def write(content, filename):
    path = os.path.join(ASSETS_DIR, filename)
    with open(path, "w") as f:
        f.write(content)
    print(f"wrote {filename}")


def main():
    if not GH_LOGIN:
        raise SystemExit("GH_LOGIN environment variable is required")
    repos = fetch_public_repos()
    repos_by_name = {r["name"]: r for r in repos}

    build_self_rated_radar()
    lang_totals = build_language_radar(repos)
    build_stat_card(repos, lang_totals)
    build_project_cards(repos_by_name)


if __name__ == "__main__":
    main()
